export const FETCH_MEASURES = 'FETCH_MEASURES';
export const FETCH_MEASURE = 'FETCH_MEASURE';
export const FETCH_OPTIONS = 'FETCH_OPTIONS';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const CREATE_MEASURE = 'CREATE_MEASURE';
