export const FETCH_MEASURES = 'FETCH_MEASURES';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const FETCH_SELECTED_MEASURE = 'FETCH_SELECTED_MEASURE';
export const FETCH_SETUP = 'FETCH_SETUP';
